In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [17]:
import pandas as pd
import glob

files = glob.glob("../data/*.csv")   # folder where all CSVs are stored

dfs = []

for f in files:
    print("\n📌 File:", f)
    df = pd.read_csv(f)
    dfs.append(df)
    print(df.head())
    print(df.info())
    print(df.columns)
    print("-" * 50)

📌 File: ../data\app_store_reviews_complete.csv
              author  rating                            title  \
0          Joyal J F       2  Accessibility and other problem
1    Kannada Chandru       5                             Good
2              VDKmm       5                            Mallu
3          Mohan8889       2          Do NOT buy Digital gold
4  Harvindra singhal       5         Fastest service phone or

                                             content  \
0  This app is not very accessible for visually, ...
1                                          Very nice
2                                             Malesh
3  Please do NOT purchase Gold in digital gold. I...
4          Good and fastest services and easy access

                        date     version  vote_count
0  2025-11-13T18:42:20-07:00  25.1031.00           0
1  2025-11-13T06:03:06-07:00  25.1031.00           0
2  2025-11-13T05:59:23-07:00  25.1031.00           0
3  2025-11-13T05:42:49-07:00  25.1031.00           0
4  2025-11-13T04:06:39-07:00  25.1031.00           0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   author      500 non-null    object
 1   rating      500 non-null    int64
 2   title       500 non-null    object
 3   content     500 non-null    object
 4   date        500 non-null    object
 5   version     500 non-null    object
 6   vote_count  500 non-null    int64
dtypes: int64(2), object(5)
memory usage: 27.5+ KB
None
Index(['author', 'rating', 'title', 'content', 'date', 'version',
       'vote_count'],
      dtype='object')
--------------------------------------------------

📌 File: ../data\combined_reviews.csv
          text  rating            timestamp app_version       source
0         good     4.0  2025-11-13 19:41:38  25.10.03.0  google_play
1  very nice 👍     5.0  2025-11-13 19:40:06  25.10.03.0  google_play
2         good     5.0  2025-11-13 19:36:58         NaN  google_play
3         good     5.0  2025-11-13 19:34:12  25.10.03.0  google_play
4           ok     5.0  2025-11-13 19:32:47  25.10.03.0  google_play
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1079 entries, 0 to 1078
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   text         1079 non-null   object
 1   rating       1000 non-null   float64
 2   timestamp    1079 non-null   object
 3   app_version  834 non-null    object
 4   source       1079 non-null   object
dtypes: float64(1), object(4)
memory usage: 42.3+ KB
None
Index(['text', 'rating', 'timestamp', 'app_version', 'source'], dtype='object')
--------------------------------------------------

📌 File: ../data\dataset_apple-app-store-review-scraper.csv
           author                                            content  \
0         Parayya                     Excellent and reliable service
1       nephsterr  I am currently using an iPhone 7 Plus and have...
2      Mojourjojo  Popping up instant notifications for advertisi...
3  Good providers                                 Very good service.
4       Dev sidar                                               Good

                        date  rating                    title     version
0  2025-11-12T03:25:32-07:00       5                  Parayya  25.1017.05
1  2025-11-03T20:37:29-07:00       1        iOS not supported  25.0613.05
2  2025-10-30T04:12:18-07:00       1  Marketing notifications  25.1017.00
3  2025-10-26T07:18:44-07:00       5     Good and convenient.  25.1003.06
4  2025-10-22T18:19:29-07:00       5                     Good  25.1003.00
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   author   25 non-null     object
 1   content  25 non-null     object
 2   date     25 non-null     object
 3   rating   25 non-null     int64
 4   title    25 non-null     object
 5   version  25 non-null     object
dtypes: int64(1), object(5)
memory usage: 1.3+ KB
None
Index(['author', 'content', 'date', 'rating', 'title', 'version'], dtype='object')
--------------------------------------------------

📌 File: ../data\dataset_twitter-keywords-scraper_2025-11-15_05-32-47-048.csv
       author_name  author_username  bookmarks_count hashtags/0    hashtags/1  \
0  Kuldeep_Saffron  kuldeeppathak00                0        NaN           NaN
1            Amish   PaisaPrinciple              153   Cashback       CCGeeks
2     amit_raj ⧉ ◎    amitraj244416                0    phonepe       upilite
3          Kaushal         kaushalc                0        NaN           NaN
4              NaN  EntrepreneurInd                0     Update  FintechIndia

  hashtags/2  hashtags/3 hashtags/4 hashtags/5 hashtags/6  ...  \
0        NaN         NaN        NaN        NaN        NaN  ...
1     CCGeek         NaN        NaN        NaN        NaN  ...
2        NaN         NaN        NaN        NaN        NaN  ...
3        NaN         NaN        NaN        NaN        NaN  ...
4    PhonePe  AIMakeover      Paytm     OpenAI       Groq  ...

                                           tweet_url  \
0  https://twitter.com/kuldeeppathak00/status/198...
1  https://twitter.com/PaisaPrinciple/status/1988...
2  https://twitter.com/amitraj244416/status/19852...
3  https://twitter.com/kaushalc/status/1988583530...
4  https://twitter.com/EntrepreneurIND/status/198...

                      urls/0 urls/1  urls/2 urls/3 urls/4 urls/5 urls/6  \
0                        NaN    NaN     NaN    NaN    NaN    NaN    NaN
1                        NaN    NaN     NaN    NaN    NaN    NaN    NaN
2                        NaN    NaN     NaN    NaN    NaN    NaN    NaN
3                        NaN    NaN     NaN    NaN    NaN    NaN    NaN
4  https://ow.ly/jNIm50Xs3a0    NaN     NaN    NaN    NaN    NaN    NaN

  urls/7 views_count
0    NaN         700
1    NaN       14150
2    NaN         440
3    NaN          81
4    NaN          45

[5 rows x 51 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 362 entries, 0 to 361
Data columns (total 51 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   author_name        357 non-null    object
 1   author_username    362 non-null    object
 2   bookmarks_count    362 non-null    int64
 3   hashtags/0         106 non-null    object
 4   hashtags/1         81 non-null     object
 5   hashtags/2         74 non-null     object
 6   hashtags/3         43 non-null     object
 7   hashtags/4         34 non-null     object
 8   hashtags/5         21 non-null     object
 9   hashtags/6         15 non-null     object
 10  hashtags/7         9 non-null      object
 11  hashtags/8         5 non-null      object
 12  keyword            362 non-null    object
 13  likes_count        362 non-null    int64
 14  media_urls/0/type  194 non-null    object
 15  media_urls/0/url   194 non-null    object
 16  media_urls/1/type  82 non-null     object
 17  media_urls/1/url   82 non-null     object
 18  media_urls/2/type  22 non-null     object
 19  media_urls/2/url   22 non-null     object
 20  media_urls/3/type  12 non-null     object
 21  media_urls/3/url   12 non-null     object
 22  media_urls/4/type  2 non-null      object
 23  media_urls/4/url   2 non-null      object
 24  media_urls/5/type  2 non-null      object
 25  media_urls/5/url   2 non-null      object
 26  media_urls/6/type  1 non-null      object
 27  media_urls/6/url   1 non-null      object
 28  media_urls/7/type  1 non-null      object
 29  media_urls/7/url   1 non-null      object
 30  mentions/0         85 non-null     object
 31  mentions/1         43 non-null     object
 32  mentions/2         31 non-null     object
 33  mentions/3         6 non-null      object
 34  mentions/4         1 non-null      object
 35  replies_count      362 non-null    int64
 36  retweets_count     362 non-null    int64
 37  scraped_at         362 non-null    object
 38  text               362 non-null    object
 39  timestamp          362 non-null    object
 40  tweet_id           362 non-null    int64
 41  tweet_url          362 non-null    object
 42  urls/0             60 non-null     object
 43  urls/1             12 non-null     object
 44  urls/2             2 non-null      object
 45  urls/3             2 non-null      object
 46  urls/4             2 non-null      object
 47  urls/5             2 non-null      object
 48  urls/6             2 non-null      object
 49  urls/7             2 non-null      object
 50  views_count        362 non-null    int64
dtypes: int64(6), object(45)
memory usage: 144.4+ KB
None
Index(['author_name', 'author_username', 'bookmarks_count', 'hashtags/0',
       'hashtags/1', 'hashtags/2', 'hashtags/3', 'hashtags/4', 'hashtags/5',
       'hashtags/6', 'hashtags/7', 'hashtags/8', 'keyword', 'likes_count',
       'media_urls/0/type', 'media_urls/0/url', 'media_urls/1/type',
       'media_urls/1/url', 'media_urls/2/type', 'media_urls/2/url',
       'media_urls/3/type', 'media_urls/3/url', 'media_urls/4/type',
       'media_urls/4/url', 'media_urls/5/type', 'media_urls/5/url',
       'media_urls/6/type', 'media_urls/6/url', 'media_urls/7/type',
       'media_urls/7/url', 'mentions/0', 'mentions/1', 'mentions/2',
       'mentions/3', 'mentions/4', 'replies_count', 'retweets_count',
       'scraped_at', 'text', 'timestamp', 'tweet_id', 'tweet_url', 'urls/0',
       'urls/1', 'urls/2', 'urls/3', 'urls/4', 'urls/5', 'urls/6', 'urls/7',
       'views_count'],
      dtype='object')
--------------------------------------------------

📌 File: ../data\phonepe_playstore_reviews.csv
                               reviewId         userName  \
0  e90f449f-c26b-4076-a1a0-c822e9df722b  Madhavi Vagdiya
1  7d79bdec-4044-4c03-b473-2a05dbae73ff    Bimal Pradhan
2  3680fb30-c0d3-40db-9a27-8b3e3dbbbef3   Serek Debbarma
3  7fcea3bd-7bc5-4a01-b594-e85c67379213       Sonu Kumar
4  70c0b297-f3ad-4342-a43c-e27d58188421          Sk Riaz

                                           userImage  \
0  https://play-lh.googleusercontent.com/a-/ALV-U...
1  https://play-lh.googleusercontent.com/a/ACg8oc...
2  https://play-lh.googleusercontent.com/a-/ALV-U...
3  https://play-lh.googleusercontent.com/a-/ALV-U...
4  https://play-lh.googleusercontent.com/a/ACg8oc...

                         content  score  thumbsUpCount reviewCreatedVersion  \
0                           good      5              0           25.10.03.0
1                         good 😊      5              0           25.10.03.0
2  its good to be in transaction      5              0           25.09.05.0
3                             ok      5              0           25.10.03.0
4                            wow      5              0           25.09.19.0

                    at replyContent repliedAt  appVersion
0  2025-11-14 04:17:54          NaN       NaN  25.10.03.0
1  2025-11-14 04:17:42          NaN       NaN  25.10.03.0
2  2025-11-14 04:17:31          NaN       NaN  25.09.05.0
3  2025-11-14 04:17:31          NaN       NaN  25.10.03.0
4  2025-11-14 04:15:32          NaN       NaN  25.09.19.0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   reviewId              5000 non-null   object
 1   userName              5000 non-null   object
 2   userImage             5000 non-null   object
 3   content               5000 non-null   object
 4   score                 5000 non-null   int64
 5   thumbsUpCount         5000 non-null   int64
 6   reviewCreatedVersion  4300 non-null   object
 7   at                    5000 non-null   object
 8   replyContent          600 non-null    object
 9   repliedAt             600 non-null    object
 10  appVersion            4300 non-null   object
dtypes: int64(2), object(9)
memory usage: 429.8+ KB
None
Index(['reviewId', 'userName', 'userImage', 'content', 'score',
       'thumbsUpCount', 'reviewCreatedVersion', 'at', 'replyContent',
       'repliedAt', 'appVersion'],
      dtype='object')
--------------------------------------------------

In [14]:
df= pd.read_csv("../data/app_store_reviews_complete.csv")

In [15]:
df.head()

,author,rating,title,content,date,version,vote_count
0,Joyal J F,2,Accessibility and other problem,"This app is not very accessible for visually, ...",2025-11-13T18:42:20-07:00,25.1031.00,0
1,Kannada Chandru,5,Good,Very nice,2025-11-13T06:03:06-07:00,25.1031.00,0
2,VDKmm,5,Mallu,Malesh,2025-11-13T05:59:23-07:00,25.1031.00,0
3,Mohan8889,2,Do NOT buy Digital gold,Please do NOT purchase Gold in digital gold. I...,2025-11-13T05:42:49-07:00,25.1031.00,0
4,Harvindra singhal,5,Fastest service phone or,Good and fastest services and easy access,2025-11-13T04:06:39-07:00,25.1031.00,0

In [16]:
len(df)

500

In [19]:
df = pd.read_csv("C:/Users/HP/Desktop/Interview Prep/Projects/InsightIO/cleaned_reviews.csv")

df.head()

,review_text,rating,author,date,app_version,source,language,sentiment
0,"this app is not very accessible for visually, ...",2.0,Joyal J F,2025-11-13T18:42:20-07:00,25.1031.00,app_store_reviews_complete.csv,en,-0.489183
1,very nice,5.0,Kannada Chandru,2025-11-13T06:03:06-07:00,25.1031.00,app_store_reviews_complete.csv,cs,0.780000
2,malesh,5.0,VDKmm,2025-11-13T05:59:23-07:00,25.1031.00,app_store_reviews_complete.csv,sq,0.000000
3,please do not purchase gold in digital gold. i...,2.0,Mohan8889,2025-11-13T05:42:49-07:00,25.1031.00,app_store_reviews_complete.csv,en,0.000000
4,good and fastest services and easy access,5.0,Harvindra singhal,2025-11-13T04:06:39-07:00,25.1031.00,app_store_reviews_complete.csv,en,0.566667

In [21]:
len(df)

5224